retrieve_data:
  description: >
    Retrieve the data from the knowledge base based on the user's input:{user_question} 
  expected_output: >
    A list of all possible data which could be relevent to the user's input
  agent: data_extractor

summarize_data:
  description: >
    Summarization of the extracted data, which is relevant to the users question:{user_question}.
     
  expected_output: >
    A list of summarized data using bulletpoints
    formatted markdown without '```'
  agent: data_summarizer
