joke_task:
  description: >
    Create a list of 10 jokes 
  expected_output: >
    A list with 10 bullet points of jokes
  agent: joke_creator

add_emopjis_task:
  description: >
    Add emojis to the list of jokes
  expected_output: >
    A list of 10 bulletpoints of jokes with emojis
    formatted markdown without '```'
  agent: add_emojis
