retrieve_data:
  description: >
    Retrieve the data from the knowledge base based on the user's input:{user_question} 
  expected_output: >
    A list of all possible data which could be relevent to the user's input
  agent: data_extractor

summarize_data:
  description: >
    Summarize the data extracted from the research task
    You also have to filter out the data which is not relevant to the user's question,
    users question:{user_question}.
    If there was no data found or the provided data is not relevant to the user's question,
    then return a message "No data found".
     
  expected_output: >
    A list of summarized data using bulletpoints
    formatted markdown without '```'
  agent: data_summarizer

add_joke:
  description: >
    Based on the text which was retrieved, create a joke that is funny and relevant to the text at the end of each summary.
    Do not repeat the jokes that you have previously made
  expected_output: >
    At the end of the retrieved text add a joke
  agent: standup_comedian